### ISSUE TITLE
Create Book list

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#1]
### Value statement
__________________________________________________________________________________________

As a **user**
I need a **list of my books**
so that **I can overview all my books.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-11-15-1926](https://user-images.githubusercontent.com/66831474/99193432-17dfc880-2779-11eb-927b-521eb554689f.png)

### Acceptance criteria
__________________________________________________________________________________________
- [x] BookCards are listed in two Colums with Picture an description.

### Tasks
___________________________________________________________________________________________
- [x] Create feature branch
- [x] Create BookCard component in Styleguidist
- [x] Create BookList component in Styleguidist
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

### Complexity
___________________________________________________________________________________________
low
