### ISSUE TITLE
Add SearchBox for easy Book adding

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#11]
### Value statement
__________________________________________________________________________________________

As a **user**
I need **a SearchBox.**
so that **I can search for a book with titel, author or ISBN.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-11-25-0924(1)](https://user-images.githubusercontent.com/66831474/100204494-3590f880-2f04-11eb-97f4-a7b63b6987fb.png)

### Acceptance criteria
__________________________________________________________________________________________

- [x] Search input field
- [x] OnChange triggers search in the API
- [x] Filters Book thumbnails
- [x] By submit BookCard is added to BookList.

### Tasks
___________________________________________________________________________________________
- [x] Create feature branch
- [x] Add to SearchField to AddBookFormModal in Styleguidist
- [x] Create BookThumb Component in Styleguidist
- [x] Remove InputFields title, author and description
- [x] Create API fetch file (getData.js) in service-folder
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

### Complexity
___________________________________________________________________________________________
medium
