### ISSUE TITLE
Create Book Detail View

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#12]
### Value statement
__________________________________________________________________________________________

As a **user**
I need **a DetailView of my Book.**
so that **I can see, if I read it or not.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-12-07-1117(1)](https://user-images.githubusercontent.com/66831474/101339299-84cd1680-387e-11eb-818c-d706f145e255.png)

### Acceptance criteria
__________________________________________________________________________________________

- [x] BookDetailView is a Modal shows by onClick BookThumbnail.

### Tasks
___________________________________________________________________________________________
- [x] Create feature branch
- [x] Add BookDetailView
- [x] Write component tests
- [x] Add components to app 
- [x] Add missing styles

### Complexity
___________________________________________________________________________________________
medium
