### ISSUE TITLE
Add Express server

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#16]
### Value statement
__________________________________________________________________________________________

As a **user**
I need **a server.**
so that **I can manage the api requests.**

### Acceptance criteria
__________________________________________________________________________________________

- [x] Private access token not accessible in the front end

### Tasks
___________________________________________________________________________________________
- [x] Add Express.js server
- [x] Add fetch logic

### Complexity
___________________________________________________________________________________________
low
