### ISSUE TITLE
Navigation Routing

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#18]
### Value statement
__________________________________________________________________________________________

As a **user**
I need **a navigation.**
so that **I move easy trough the app.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-12-07-1117](https://user-images.githubusercontent.com/66831474/101339234-6c5cfc00-387e-11eb-9429-6a82d0834212.png)

### Acceptance criteria
__________________________________________________________________________________________

- [ ] The usercan move between home and search page by button toggle.

### Tasks
___________________________________________________________________________________________
- [ ] Create feature branch
- [ ] Add react-router
- [ ] Add react-router dynamic URL
- [ ] Add loading logic
- [ ] Write component tests
- [ ] Add components to home and search page
- [ ] Add missing styles

### Complexity
___________________________________________________________________________________________
medium
