### ISSUE TITLE
Add BookCards to BookList

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#2]
### Value statement
__________________________________________________________________________________________

As a **user**
I need to **add books**
so that **I can add books by myself.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-11-15-1926(10)](https://user-images.githubusercontent.com/66831474/99874843-1edc6000-2beb-11eb-86c5-d646dafe0168.png)

### Acceptance criteria
__________________________________________________________________________________________

- [x] Title and Author are required, submit button is disabled, if fields are empty.
- [x] Cover and Description are optional.
- [x] By Submit BookCard is added to BookList.
- [x] Modal are closed by Button.

### Tasks
___________________________________________________________________________________________
- [x] Create feature branch
- [x] Create CircleButton component in Styleguidist
- [x] Create RectangleButton component in Styleguidist
- [x] Create AddBookForm component in Styleguidist
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

### Complexity
___________________________________________________________________________________________
medium
