### ISSUE TITLE
Remove BookCards from BookList

### ISSUE THREAD

**Issue by CinFrei** [CinFrei/capstone-project#3]
### Value statement
__________________________________________________________________________________________

As a **user**
I need to **remove books from a list**
so that **I can remove books by myself.**

### Description (Text, Scribble, Wireframe, Design)
__________________________________________________________________________________________
![Untitled-2020-11-15-1926(2)](https://user-images.githubusercontent.com/66831474/99193773-77d76e80-277b-11eb-9c57-f29debe53af4.png)

### Acceptance criteria
__________________________________________________________________________________________
- [x] Book are removed from the list by button click.

### Tasks
___________________________________________________________________________________________
- [x] Create feature branch
- [x] Create a Remove Button in the BooksCard Component
- [x] Write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

### Complexity
___________________________________________________________________________________________
medium
